[tool.poetry]
name = "nix-alien"
version = "0.1.0"
description = "Run unpatched binaries on Nix/NixOS"
authors = ["Thiago Kenji Okada <thiagokokada@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
# Setting it this way since this is the minimum version supported by python-fzf
python = "^3.9.2"
pylddwrap = "^1.2.1"
python-fzf = "^0.1.1"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
pytest = "^6.2.5"
mypy = "^0.910"

[tool.poetry.scripts]
nix-alien = "nix_alien.fhs_env:main"
nix-alien-ld = "nix_alien.nix_ld:main"
nix-alien-find-libs = "nix_alien.libs:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
