[tool.poetry]
name = "nix-alien"
version = "0.1.0"
description = "Run unpatched binaries on Nix/NixOS"
authors = ["Thiago Kenji Okada <thiagokokada@gmail.com>"]
license = "MIT"
include = ["nix_alien/*.nix", "nix_alien/version"]

[tool.poetry.dependencies]
python = "^3.9"
pylddwrap = "^1.2.1"
pyfzf = "^0.3.1"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
pytest = "^6.2.5"
mypy = "^0.940"
# TODO: remove after this issue is fixed
# https://github.com/nix-community/poetry2nix/pull/600
platformdirs = "2.5.1"

[tool.poetry.scripts]
nix-alien = "nix_alien.fhs_env:main"
nix-alien-ld = "nix_alien.nix_ld:main"
nix-alien-find-libs = "nix_alien.libs:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
