name: ci

on:
  push:

jobs:
  build-x86_64-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: CI
        run: nix flake check

  build-aarch64-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install QEMU
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update -q -y
          sudo apt-get install -q -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            extra-platforms = aarch64-linux

      - name: CI
        # We are running all linters in x86_64 already, no need to rerun them here
        run: nix build --option system aarch64-linux
